name: 'Terraform React Deploy To AWS'
description: 'Deploy a React app using Terraform and S3'

inputs:
  project-name:
    description: 'The project name used for naming resources and tags'
    required: true

  project-type:
    description: 'The project name used for naming resources and tags'
    required: true

  terraform-dir:
    description: 'Directory where the Terraform code is located'
    required: true

  aws-region:
    description: 'AWS region for deployment'
    required: false
    default: 'us-east-1'

  domain-name:
    description: 'Domain name to check for an existing hosted zone'
    required: true

  subdomain:
    description: 'Subdomain of the app'
    required: true

  bucket-name:
    description: 'Custom S3 bucket name'
    required: false
    default: 'null'

  environment:
    description: 'Deployment environment (e.g., dev, prod, staging)'
    required: false
    default: 'dev'

  create-zone:
    description: 'Create a new Route 53 hosted zone'
    required: false
    default: 'false'

  tags:
    description: 'Tags to apply to the resources'
    required: false
    default: 'null'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set S3 bucket name
      id: bucket_name
      shell: bash
      run: |
        if [ "${{ inputs.s3-bucket-name }}" != "null" ]; then
          echo "s3_bucket_name=${{ inputs.s3-bucket-name }}" >> $GITHUB_ENV
        else
          echo "s3_bucket_name=${{ inputs.project-name }}-${{ inputs.environment }}-s3" >> $GITHUB_ENV
        fi

    - name: Determine Environment from Branch
      id: env
      shell: bash
      run: |
        case ${GITHUB_REF_NAME} in
          "dev"|"develop") echo "environment=dev" >> $GITHUB_ENV ;;
          "prod"|"main") echo "environment=prod" >> $GITHUB_ENV ;;
          "staging") echo "environment=staging" >> $GITHUB_ENV ;;
          *) echo "environment=dev" >> $GITHUB_ENV ;;
        esac

    - name: Check if Hosted Zone Exists
      id: hosted_zone_check
      shell: bash
      run: |
        ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name ${{ inputs.domain }} --query "HostedZones[0].Id" --output text)
        if [ "$ZONE_ID" != "None" ]; then
          echo "Hosted Zone exists. Setting create_zone to false"
          echo "create_zone=false" >> $GITHUB_ENV
        else
          echo "Hosted Zone does not exist. Setting create_zone to true"
          echo "create_zone=true" >> $GITHUB_ENV
        fi

    - name: Terraform Init
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: terraform init

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: |
        terraform plan -out=tfplan \
          -var "project_name=${{ inputs.project-name }}" \
          -var "project_type=${{ inputs.project-type }}" \
          -var "domain_name=${{ inputs.domain-name }}" \
          -var "aws_region=${{ inputs.aws-region }}" \
          -var "environment=${{ env.environment }}" \
          -var "bucket_name=${{ inputs.bucket-name }}" \
          -var "create_zone=${{ inputs.create-zone }}" \
          -var='tags={"Name"="${{ inputs.project-name }}", "ManagedBy"="Terraform", "Project"="${{ inputs.project-type }}"}'

    - name: Terraform Apply
      id: apply
      continue-on-error: true
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: |
        if terraform apply -auto-approve tfplan; then
          echo "Terraform apply succeeded"
          echo "apply_success=true" >> $GITHUB_ENV
          echo "apply_success=true" >> $GITHUB_OUTPUT
        else
          echo "Terraform apply failed"
          echo "apply_success=false" >> $GITHUB_ENV
          echo "apply_success=false" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Terraform Destroy on Failure
      if: steps.apply.outputs.apply_success == 'false'
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: |
        echo "Cleaning up resources with terraform destroy..."
        terraform destroy -auto-approve \
          -var "project_name=${{ inputs.project-name }}" \
          -var "project_type=${{ inputs.project-type }}" \
          -var "domain_name=${{ inputs.domain-name }}" \
          -var "aws_region=${{ inputs.aws-region }}" \
          -var "environment=${{ env.environment }}" \
          -var "bucket_name=${{ inputs.bucket-name }}" \
          -var "create_zone=${{ inputs.create-zone }}" \
          -var='tags={"Name"="${{ inputs.project-name }}", "ManagedBy"="Terraform", "Project"="${{ inputs.project-type }}"}'

    - name: Get Terraform Outputs
      if: steps.apply.outputs.apply_success == 'true'
      id: get_outputs
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: |
        S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")
        if [ -n "$S3_BUCKET_NAME" ]; then
          echo "s3_bucket_name=$S3_BUCKET_NAME" >> "$GITHUB_OUTPUT"
        else
          echo "s3_bucket_name=" >> "$GITHUB_OUTPUT"
          echo "Warning: s3_bucket_name output not found in Terraform" >&2
        fi

        WEBSITE_ENDPOINT=$(terraform output -raw website_endpoint 2>/dev/null || echo "")
        if [ -n "$WEBSITE_ENDPOINT" ]; then
          echo "website_endpoint=$WEBSITE_ENDPOINT" >> "$GITHUB_OUTPUT"
        else
          echo "website_endpoint=" >> "$GITHUB_OUTPUT"
          echo "Warning: website_endpoint output not found in Terraform" >&2
        fi

    - name: Notify on Timeout or Failure
      if: failure() || cancelled()
      shell: bash
      run: |
        echo "Deployment failed or timed out. Check AWS status and logs."

outputs:
  s3_bucket_name:
    description: 'The name of the S3 bucket created or used'
    value: ${{ steps.get_outputs.outputs.s3_bucket_name }}
  website_endpoint:
    description: 'S3 static website endpoint'
    value: ${{ steps.get_outputs.outputs.website_endpoint }}
